version: '3.3'

services:
  mysql:
    image: mysql:5
    container_name: mysql_container
    environment:
      MYSQL_DATABASE: mate_drinker
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: sdiaz
      MYSQL_PASSWORD: admin123
    ports:
      - 3307:3306
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - PMA_HOST=mysql
    ports:
      - 8080:80


